[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "meowdy"
version = "0.1.0"

[dependencies]
bevy = {version = "0.6.1"}
bevy-inspector-egui = "0.8.2"
bevy_asset_loader = "0.9.0"
clap = { version = "3.1.6", features = ["derive"] }
tracing = "0.1.32"
